### PR TITLE
feat: use plausible for tracking

### PR DESCRIPTION
**Pull request by zeitgeist**
Adds integration for plausible.io-based tracking:

1. if the environment variable `NEXT_PUBLIC_PLAUSIBLE_DOMAIN` is set, then
2. add the plausible script header and use the domain from above var accordingly

### CODE REVIEW

**Review by fkettelhoit — APPROVED** [review]

**Review by raimundo-henriques — APPROVED** [review]

**Comment by zeitgeist** [comment]
re-worked this whole PR to use package `next-plausible` . Please review

**Comment by zeitgeist** [comment]
also updated the Vercel project definition here: https://vercel.com/wbcsd/pact-catalog-frontend

Before deploying this PR, we also need to update this project, don't we @raimundo-henriques: https://vercel.com/wbcsd/pact-catalog ?

**Comment by raimundo-henriques** [comment]
Thank you, @zeitgeist, looks great!
If I'm not wrong, the only thing we need to do in the https://vercel.com/wbcsd/pact-catalog project is to update environment variables to match the ones on the pact-catalog-frontend repo. I can take care of that!

**Review by raimundo-henriques — APPROVED** [review]

**Review by fkettelhoit — APPROVED** [review]

**Comment by zeitgeist** [comment]
@raimundo-henriques that's correct. I'll go ahead and add this to the `pact-catalog` project and merge this PR

**Comment by zeitgeist** [comment]
you already did this, @raimundo-henriques . Much appreciated!

**Pull request merged**
